-- MySQL Script generated by MySQL Workbench
-- Sun Jul 30 07:36:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema content
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `content` ;

-- -----------------------------------------------------
-- Schema content
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `content` DEFAULT CHARACTER SET utf8 ;
USE `content` ;

-- -----------------------------------------------------
-- Table `content`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content`.`users` ;

CREATE TABLE IF NOT EXISTS `content`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `nickname` VARCHAR(10) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `content`.`contents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content`.`contents` ;

CREATE TABLE IF NOT EXISTS `content`.`contents` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `text` TEXT NOT NULL,
  `userId` BIGINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
